version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/Troumaca-web
hooks:
  AfterInstall:
    - location: scripts/stop.sh
      runas: ec2-user
  ApplicationStart:
    - location: scripts/run.sh
      runas: ec2-user
