version: 0.2

phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
      - npm install -g @angular/cli
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm build --base-href ./
  post_build:
    commands:
      - echo Build completed on `date`
      - ls
      - cp appspec.yml dist
      - ls
      - cp -r node_modules dist
      - ls
      - cp -r scripts dist
      - ls
      - cd dist
      - ls
      - zip -r troumaca-web.zip *
      - mv troumaca-web.zip ../
      -ls
artifacts:
    files:
      - troumaca-web.zip
