version: 0.2

phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
      - npm i npm@latest -g
      - npm install -g @angular/cli@latest
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - ng build --prod
  post_build:
    commands:
      - ls
      - pwd
      - cp appspec.yml dist
      - cp server.js dist
      - cp package.json dist
      - cp scripts/* dist
      - cp node_modules/* dist
      - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: no
