version: 0.2

phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
      - npm install -g @angular/cli
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - ng build --prod
  post_build:
    commands:
      - cp appspec.yml dist
      - cp server.js dist
      - cp package.json dist
      - cp -r scripts dist
      - cp -r node_modules dist
      - cp src/favicon.png dist
      - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: no
