/** Declaration file generated by dts-gen */

export = generate_sms_verification_code;

declare function generate_sms_verification_code(length: any, options: any): any;

declare namespace generate_sms_verification_code {
    const prototype: {
    };

}

